services:
  client:
    image: ghcr.io/${GHCR_USER}/tb-gcc-compiler-optimization:v1
    pull_policy: always
    network_mode: host
    container_name: ${T_BENCH_TASK_DOCKER_CLIENT_CONTAINER_NAME}
    command:
    - sh
    - -c
    - echo 'APT::Sandbox::User "root";' > /etc/apt/apt.conf.d/99no-sandbox; mkdir
      -p /etc/dpkg/dpkg.cfg.d; echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/99unsafe-io;
      sleep infinity
    environment:
    - TEST_DIR=${T_BENCH_TEST_DIR}
    - TAR_OPTIONS=--no-same-owner
    volumes:
    - ${T_BENCH_TASK_LOGS_PATH}:${T_BENCH_CONTAINER_LOGS_PATH}
    - ${T_BENCH_TASK_AGENT_LOGS_PATH}:${T_BENCH_CONTAINER_AGENT_LOGS_PATH}
